#!/usr/bin/env zsh

##
# fzf-rm
#
# https://github.com/beauwilliams/awesome-fzf
#
# Alias this function to `rm`.  You can then use `rm` with no arguments to use multi select with fzf.

function fzf-rm() {
  if [[ "$#" -eq 0 ]]; then
    local files
    files=$(find . -maxdepth 1 -type f | fzf --multi)
    echo $files | xargs -I '{}' rm {} #we use xargs to capture filenames with spaces in them properly
  else
    command rm "$@"
  fi
}
