#!/usr/bin/env zsh

##
# zstats
#
# Analyze the last 1000 commands for most frequently used.

function zstats() {
    history 1000 | awk '{CMD[$2]++;count++;}END { for (a in CMD)print CMD[a] " " CMD[a]/count*100 "% " a;}' | grep -v "./" | column -c3 -s " " -t | sort -nr | nl | head -n10
}
